export interface Tweet {
  Identifier: string;
  Content: string;
  Timestamp: string;
  Sentiment: "positive" | "negative" | "neutral";
  Sentiment_Score: number;
  Custom_Category: string;
  Custom_Score: number;
}

export interface Answer {
  Category: string;
  Answer_Number: number;
  Content: string;
  Timestamp: string;
  Sentiment: "positive" | "negative" | "neutral";
  Sentiment_Score: number;
  Custom_Category: string;
  Custom_Score: number;
}

export const mockData = {
  message: "Scraping for user elonmusk completed.",
  results: {
    tweets_analysis: [
      {
        Identifier: "tweet1",
        Content: "The elections this year seem more intense than ever.",
        Timestamp: "2024-11-10T08:15:30.000Z",
        Sentiment: "positive",
        Sentiment_Score: 0.8765,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet2",
        Content: "Why do people still fall for fake news?",
        Timestamp: "2024-11-10T09:45:15.000Z",
        Sentiment: "negative",
        Sentiment_Score: 0.2314,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet3",
        Content: "I'm excited to see how the candidates debate tonight.",
        Timestamp: "2024-11-10T10:20:50.000Z",
        Sentiment: "positive",
        Sentiment_Score: 0.6432,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet4",
        Content: "It feels like every news channel has a different agenda.",
        Timestamp: "2024-11-10T11:05:40.000Z",
        Sentiment: "neutral",
        Sentiment_Score: 0.5481,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet5",
        Content: "The recent news coverage has been disappointing.",
        Timestamp: "2024-11-10T12:30:25.000Z",
        Sentiment: "negative",
        Sentiment_Score: 0.4023,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet6",
        Content: "I think the political landscape is changing rapidly.",
        Timestamp: "2024-11-10T13:50:30.000Z",
        Sentiment: "neutral",
        Sentiment_Score: 0.6912,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet7",
        Content: "Social media is influencing opinions more than ever.",
        Timestamp: "2024-11-10T14:30:15.000Z",
        Sentiment: "positive",
        Sentiment_Score: 0.7254,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet8",
        Content: "Another scandal in the news today. Unbelievable.",
        Timestamp: "2024-11-10T15:15:10.000Z",
        Sentiment: "negative",
        Sentiment_Score: 0.3178,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet9",
        Content: "Hope this election season ends soon.",
        Timestamp: "2024-11-10T16:40:55.000Z",
        Sentiment: "neutral",
        Sentiment_Score: 0.5801,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet10",
        Content: "Can’t believe the amount of misinformation spreading.",
        Timestamp: "2024-11-10T18:05:50.000Z",
        Sentiment: "negative",
        Sentiment_Score: 0.2911,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet11",
        Content: "What a great speech! Gave me hope for the future.",
        Timestamp: "2024-11-11T07:15:35.000Z",
        Sentiment: "positive",
        Sentiment_Score: 0.8654,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet12",
        Content: "Too many ads, not enough actual information.",
        Timestamp: "2024-11-11T08:25:45.000Z",
        Sentiment: "negative",
        Sentiment_Score: 0.3594,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet13",
        Content: "I am unsure who to believe at this point.",
        Timestamp: "2024-11-11T09:40:10.000Z",
        Sentiment: "neutral",
        Sentiment_Score: 0.505,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet14",
        Content: "Politicians should focus on real issues.",
        Timestamp: "2024-11-11T10:15:55.000Z",
        Sentiment: "negative",
        Sentiment_Score: 0.2724,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet15",
        Content: "Grateful to see some real discussions happening.",
        Timestamp: "2024-11-11T12:25:10.000Z",
        Sentiment: "positive",
        Sentiment_Score: 0.7784,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet16",
        Content: "Neutral on the whole thing. Just want peace.",
        Timestamp: "2024-11-11T13:50:20.000Z",
        Sentiment: "neutral",
        Sentiment_Score: 0.6405,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet17",
        Content: "Elections seem fair so far. Let’s see what happens.",
        Timestamp: "2024-11-11T14:35:55.000Z",
        Sentiment: "positive",
        Sentiment_Score: 0.7153,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet18",
        Content: "Can’t stand this constant negativity.",
        Timestamp: "2024-11-11T15:10:35.000Z",
        Sentiment: "negative",
        Sentiment_Score: 0.2291,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet19",
        Content: "I hope the best candidate wins!",
        Timestamp: "2024-11-11T16:05:40.000Z",
        Sentiment: "positive",
        Sentiment_Score: 0.8901,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet20",
        Content: "Just another day of biased media.",
        Timestamp: "2024-11-11T17:30:50.000Z",
        Sentiment: "neutral",
        Sentiment_Score: 0.4322,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet21",
        Content: "The future looks bright with the right leaders.",
        Timestamp: "2024-11-12T07:25:30.000Z",
        Sentiment: "positive",
        Sentiment_Score: 0.7682,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet22",
        Content: "Just can't trust what I see on TV anymore.",
        Timestamp: "2024-11-12T08:15:45.000Z",
        Sentiment: "negative",
        Sentiment_Score: 0.2845,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet23",
        Content: "Looking forward to see how this all turns out.",
        Timestamp: "2024-11-12T09:55:15.000Z",
        Sentiment: "positive",
        Sentiment_Score: 0.7834,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet24",
        Content: "This election cycle is exhausting.",
        Timestamp: "2024-11-12T10:35:20.000Z",
        Sentiment: "negative",
        Sentiment_Score: 0.3199,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet25",
        Content: "Great to see so many people engaged!",
        Timestamp: "2024-11-12T11:45:10.000Z",
        Sentiment: "positive",
        Sentiment_Score: 0.9021,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet26",
        Content: "All the ads are just too much now.",
        Timestamp: "2024-11-12T13:05:55.000Z",
        Sentiment: "negative",
        Sentiment_Score: 0.2983,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet27",
        Content: "Keeping an open mind about the whole process.",
        Timestamp: "2024-11-12T14:25:30.000Z",
        Sentiment: "neutral",
        Sentiment_Score: 0.6112,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet28",
        Content: "Some candidates have really great ideas.",
        Timestamp: "2024-11-12T15:40:15.000Z",
        Sentiment: "positive",
        Sentiment_Score: 0.7912,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet29",
        Content: "Can’t believe all the mudslinging this year.",
        Timestamp: "2024-11-12T17:55:35.000Z",
        Sentiment: "negative",
        Sentiment_Score: 0.3254,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet30",
        Content: "Waiting for election day with mixed feelings.",
        Timestamp: "2024-11-12T19:20:10.000Z",
        Sentiment: "neutral",
        Sentiment_Score: 0.5025,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet31",
        Content: "I think we need a fresh perspective.",
        Timestamp: "2024-11-12T20:55:25.000Z",
        Sentiment: "positive",
        Sentiment_Score: 0.6563,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet32",
        Content: "Another day of sensationalist headlines.",
        Timestamp: "2024-11-12T21:20:45.000Z",
        Sentiment: "negative",
        Sentiment_Score: 0.2901,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet33",
        Content: "Can’t wait for the results to come in!",
        Timestamp: "2024-11-13T06:15:30.000Z",
        Sentiment: "positive",
        Sentiment_Score: 0.8123,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet34",
        Content: "Just wish it was over already.",
        Timestamp: "2024-11-13T08:35:20.000Z",
        Sentiment: "negative",
        Sentiment_Score: 0.3405,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Identifier: "tweet35",
        Content: "Everyone is talking politics, exhausting.",
        Timestamp: "2024-11-13T10:10:55.000Z",
        Sentiment: "neutral",
        Sentiment_Score: 0.5075,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      // Continue preenchendo até 50 tweets, seguindo o mesmo padrão
    ] as Tweet[],
    answers_analysis: [
      {
        Category: "Atenção",
        Answer_Number: 1,
        Content:
          "Sim, eu me considero multitarefa e geralmente consigo lidar com várias tarefas ao mesmo tempo sem me distrair ou me cansar.",
        Timestamp: "2024-11-14T14:00:43.523087",
        Sentiment: "neutral",
        Sentiment_Score: 0.4510849118232727,
        Custom_Category: "felicidade",
        Custom_Score: 0,
      },
      {
        Category: "Atenção",
        Answer_Number: 2,
        Content:
          "Tenho mais dificuldade de manter a atenção em atividades que envolvem longas leituras ou reuniões sem interação.",
        Timestamp: "2024-11-14T14:00:43.523087",
        Sentiment: "negative",
        Sentiment_Score: 0.7393178343772888,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Category: "Confiança",
        Answer_Number: 1,
        Content:
          "Minha confiança nas pessoas de fora da família é limitada. Costumo ser cauteloso até que eu tenha uma razão para confiar.",
        Timestamp: "2024-11-14T14:00:43.523087",
        Sentiment: "neutral",
        Sentiment_Score: 0.4344845116138458,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Category: "Confiança",
        Answer_Number: 2,
        Content:
          "Eu confio em pessoas que demonstram transparência, honestidade e consistência em suas ações.",
        Timestamp: "2024-11-14T14:00:43.523087",
        Sentiment: "positive",
        Sentiment_Score: 0.801417887210846,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Category: "Liderança",
        Answer_Number: 1,
        Content:
          "Acredito que a liderança é sobre inspirar e guiar as pessoas para atingirem seus objetivos.",
        Timestamp: "2024-11-14T14:00:43.523087",
        Sentiment: "positive",
        Sentiment_Score: 0.5506334900856018,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Category: "Liderança",
        Answer_Number: 2,
        Content:
          "Mobilização, para mim, é a capacidade de motivar e envolver as pessoas em uma causa ou tarefa.",
        Timestamp: "2024-11-14T14:00:43.523087",
        Sentiment: "positive",
        Sentiment_Score: 0.5030942559242249,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Category: "Liderança",
        Answer_Number: 3,
        Content:
          "O primeiro seguidor é essencial para validar o líder e mostrar aos demais que o caminho proposto é possível.",
        Timestamp: "2024-11-14T14:00:43.523087",
        Sentiment: "positive",
        Sentiment_Score: 0.6021986603736877,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Category: "Liderança",
        Answer_Number: 4,
        Content:
          "Os demais seguidores se unem ao movimento quando veem o valor do propósito e a credibilidade do líder.",
        Timestamp: "2024-11-14T14:00:43.523087",
        Sentiment: "positive",
        Sentiment_Score: 0.5722607970237732,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Category: "Comunicação",
        Answer_Number: 1,
        Content:
          "Essa mensagem poderia soar autoritária ou pressionar o destinatário. Seria melhor formular de forma mais colaborativa.",
        Timestamp: "2024-11-14T14:00:43.523087",
        Sentiment: "negative",
        Sentiment_Score: 0.5206393003463745,
        Custom_Category: "neutral",
        Custom_Score: 0,
      },
      {
        Category: "Comunicação",
        Answer_Number: 2,
        Content:
          "Uma alternativa melhor poderia ser: 'Oi! Você acha que conseguiria terminar sua parte do projeto até a quarta-feira? Estamos com o prazo um pouco apertado.'",
        Timestamp: "2024-11-14T14:00:43.523087",
        Sentiment: "neutral",
        Sentiment_Score: 0.6758587956428528,
        Custom_Category: "felicidade",
        Custom_Score: 0,
      },
      {
        Category: "Comunicação",
        Answer_Number: 3,
        Content:
          "Para uma comunicação mais não violenta: 'Eu gostaria de saber se você poderia realizar o que combinamos, para que possamos manter o progresso.'",
        Timestamp: "2024-11-14T14:00:43.523087",
        Sentiment: "neutral",
        Sentiment_Score: 0.558908998966217,
        Custom_Category: "felicidade",
        Custom_Score: 0,
      },
      {
        Category: "Comunicação",
        Answer_Number: 4,
        Content:
          "Uma reformulação seria: 'Eu me sinto frustrado quando tenho que esperar muito por respostas. Poderíamos nos comunicar de forma mais frequente?'",
        Timestamp: "2024-11-14T14:00:43.523087",
        Sentiment: "negative",
        Sentiment_Score: 0.9012773036956787,
        Custom_Category: "tristeza",
        Custom_Score: -2,
      },
    ] as Answer[],
  },
};
